### ISSUE TITLE
mat1 and mat2 shapes cannot be multiplied (272115x2 and 100x200)

### ISSUE THREAD

**Issue by zenghaokai** [liuxiyang641/RAGAT#31]
2024-12-24 00:08:24,130 - [DEBUG] - <class 'Exception'>____mat1 and mat2 shapes cannot be multiplied (272115x2 and 100x200)
traceback.format_exc():____Traceback (most recent call last):
  File "E:\netdown\RAGAT-main\run.py", line 453, in fit
    train_loss = self.run_epoch(epoch, val_mrr)
  File "E:\netdown\RAGAT-main\run.py", line 417, in run_epoch
    pred = self.model.forward(sub, rel, neg_ent)
  File "E:\netdown\RAGAT-main\model\models.py", line 136, in forward
    sub_emb, rel_emb, all_ent = self.forward_base(sub, rel, self.hidden_drop, self.feature_drop)
  File "E:\netdown\RAGAT-main\model\models.py", line 49, in forward_base
    ent_embed1, rel_embed1 = self.conv1(x=self.init_embed, rel_embed=init_rel)
  File "E:\conda\envs\taskrecongize\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\conda\envs\taskrecongize\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\netdown\RAGAT-main\model\ragat_conv.py", line 89, in forward
    in_res1 = self.propagate('add', self.in_index, x=x, edge_type=self.in_type, rel_embed=rel_embed,
  File "E:\netdown\RAGAT-main\model\message_passing.py", line 113, in propagate
    out = self.message(*message_args)
  File "E:\netdown\RAGAT-main\model\ragat_conv.py", line 193, in message
    out = torch.mm(xj_rel, weight)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (272115x2 and 100x200)

进程已结束,退出代码0
这个是为什么啊

**Comment by liuxiyang641** [comment]
你好，
很明显是`out = torch.mm(xj_rel, weight)`这里的`xj_rel`和`weight`的张量维度不一致了，看起来是`xj_rel`的维度`272115x2`很奇怪，你debug检查下是哪个步骤导致这一问题了就好
